// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBUwBvZxjhR4TroV18M4HyVLZWLhZs1nY',
    appId: '1:295268278098:android:6dbd40b6326587fc07e48b',
    messagingSenderId: '295268278098',
    projectId: 'pinspire-e74e9',
    storageBucket: 'pinspire-e74e9.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIwVK-25SajFOHqKtgGrr6cTBggBz_IpE',
    appId: '1:295268278098:web:d8cead6a6a5b569007e48b',
    messagingSenderId: '295268278098',
    projectId: 'pinspire-e74e9',
    authDomain: 'pinspire-e74e9.firebaseapp.com',
    storageBucket: 'pinspire-e74e9.firebasestorage.app',
    measurementId: 'G-T0696TJ9JE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUEfovha42a1I5oe3hxtx1IHASrB1CvpQ',
    appId: '1:295268278098:ios:2ce5823c5819f60607e48b',
    messagingSenderId: '295268278098',
    projectId: 'pinspire-e74e9',
    storageBucket: 'pinspire-e74e9.firebasestorage.app',
    androidClientId: '295268278098-48ars3v0pp6rtbg3u8l9vl0slj132nnh.apps.googleusercontent.com',
    iosClientId: '295268278098-pa6h6pjqgha7uojojcfo1ukbi9nv4bbi.apps.googleusercontent.com',
    iosBundleId: 'com.pinspire.app',
  );
}
